export const GALLERY = [
  {
    id: 1,
    title: "Tutorial",
    image: "/assets/gallery/tutorial/1.jpg",
    videos: [
      // "https://www.youtube.com/watch?v=EvMhUnO9yBM",
      // "https://www.youtube.com/watch?v=LnI6t-nGIm4",
      // "https://www.youtube.com/watch?v=Ou_uGgsntHI"
    ],
    photos: [
      "/assets/gallery/tutorial/1.jpg",
      "/assets/gallery/tutorial/2.jpg",
      "/assets/gallery/tutorial/3.jpg",
      "/assets/gallery/tutorial/4.jpg",
      "/assets/gallery/tutorial/5.jpg",
      "/assets/gallery/tutorial/6.jpg",
      "/assets/gallery/tutorial/7.jpg",
      "/assets/gallery/tutorial/8.jpg",
      "/assets/gallery/tutorial/9.jpg",
      "/assets/gallery/tutorial/10.jpg",
      "/assets/gallery/tutorial/11.jpg",
      "/assets/gallery/tutorial/12.jpg",
      "/assets/gallery/tutorial/13.jpg",
      "/assets/gallery/tutorial/14.jpg",
      "/assets/gallery/tutorial/15.jpg",
      "/assets/gallery/tutorial/16.jpg",
      "/assets/gallery/tutorial/17.jpg",
      "/assets/gallery/tutorial/18.jpg",
      "/assets/gallery/tutorial/19.jpg",
      "/assets/gallery/tutorial/20.jpg",
    ],
  },
  {
    id: 2,
    title: "Shrine Of Renjana",
    image: "/assets/gallery/stage1/1.jpg",
    videos: [
      // "https://www.youtube.com/watch?v=EvMhUnO9yBM",
      // "https://www.youtube.com/watch?v=LnI6t-nGIm4",
      // "https://www.youtube.com/watch?v=Ou_uGgsntHI"
    ],
    photos: [
      "/assets/gallery/stage1/1.jpg",
      "/assets/gallery/stage1/2.jpg",
      "/assets/gallery/stage1/3.jpg",
      "/assets/gallery/stage1/4.jpg",
      "/assets/gallery/stage1/5.jpg",
      "/assets/gallery/stage1/6.jpg",
      "/assets/gallery/stage1/7.jpg",
      "/assets/gallery/stage1/8.jpg",
      "/assets/gallery/stage1/9.jpg",
      "/assets/gallery/stage1/10.jpg",
      "/assets/gallery/stage1/11.jpg",
      "/assets/gallery/stage1/12.jpg",
      "/assets/gallery/stage1/13.jpg",
      "/assets/gallery/stage1/14.jpg",
      "/assets/gallery/stage1/15.jpg",
      "/assets/gallery/stage1/16.jpg",
      "/assets/gallery/stage1/17.jpg",
      "/assets/gallery/stage1/18.jpg",
      "/assets/gallery/stage1/19.jpg",
      "/assets/gallery/stage1/20.jpg",
      "/assets/gallery/stage1/21.jpg",
      "/assets/gallery/stage1/22.jpg",
      "/assets/gallery/stage1/23.jpg",
      "/assets/gallery/stage1/24.jpg",
      "/assets/gallery/stage1/25.jpg",
      "/assets/gallery/stage1/26.jpg",
      "/assets/gallery/stage1/27.jpg",
      "/assets/gallery/stage1/28.jpg",
      "/assets/gallery/stage1/29.jpg",
      "/assets/gallery/stage1/30.jpg",
    ],
  },
  {
    id: 3,
    title: "Mirage In Sahara",
    image: "/assets/gallery/stage2/1.jpg",
    videos: [
      // "https://www.youtube.com/watch?v=EvMhUnO9yBM",
      // "https://www.youtube.com/watch?v=LnI6t-nGIm4",
      // "https://www.youtube.com/watch?v=Ou_uGgsntHI"
    ],
    photos: [
      "/assets/gallery/stage2/1.jpg",
      "/assets/gallery/stage2/2.jpg",
      "/assets/gallery/stage2/3.jpg",
      "/assets/gallery/stage2/4.jpg",
      "/assets/gallery/stage2/5.jpg",
      "/assets/gallery/stage2/6.jpg",
      "/assets/gallery/stage2/7.jpg",
      "/assets/gallery/stage2/8.jpg",
      "/assets/gallery/stage2/9.jpg",
      "/assets/gallery/stage2/10.jpg",
      "/assets/gallery/stage2/11.jpg",
      "/assets/gallery/stage2/12.jpg",
      "/assets/gallery/stage2/13.jpg",
      "/assets/gallery/stage2/14.jpg",
      "/assets/gallery/stage2/15.jpg",
      "/assets/gallery/stage2/16.jpg",
      "/assets/gallery/stage2/17.jpg",
      "/assets/gallery/stage2/18.jpg",
      "/assets/gallery/stage2/19.jpg",
      "/assets/gallery/stage2/20.jpg",
      // "/assets/gallery/stage2/21.jpg",
      // "/assets/gallery/stage2/22.jpg",
      // "/assets/gallery/stage2/23.jpg",
      // "/assets/gallery/stage2/24.jpg",
      // "/assets/gallery/stage2/25.jpg",
      // "/assets/gallery/stage2/26.jpg",
      // "/assets/gallery/stage2/27.jpg",
      // "/assets/gallery/stage2/28.jpg",
      // "/assets/gallery/stage2/29.jpg",
      // "/assets/gallery/stage2/30.jpg",
    ],
  },
  {
    id: 4,
    title: "Revival Of Metropolis",
    image: "/assets/gallery/stage3/1.jpg",
    videos: [
      // "https://www.youtube.com/watch?v=EvMhUnO9yBM",
      // "https://www.youtube.com/watch?v=LnI6t-nGIm4",
      // "https://www.youtube.com/watch?v=Ou_uGgsntHI"
    ],
    photos: [
      "/assets/gallery/stage3/1.jpg",
      "/assets/gallery/stage3/2.jpg",
      "/assets/gallery/stage3/3.jpg",
      "/assets/gallery/stage3/4.jpg",
      "/assets/gallery/stage3/5.jpg",
      "/assets/gallery/stage3/6.jpg",
      "/assets/gallery/stage3/7.jpg",
      "/assets/gallery/stage3/8.jpg",
      "/assets/gallery/stage3/9.jpg",
      "/assets/gallery/stage3/10.jpg",
      "/assets/gallery/stage3/11.jpg",
      "/assets/gallery/stage3/12.jpg",
      "/assets/gallery/stage3/13.jpg",
      "/assets/gallery/stage3/14.jpg",
      // "/assets/gallery/stage3/15.jpg",
      // "/assets/gallery/stage3/16.jpg",
      // "/assets/gallery/stage3/17.jpg",
      // "/assets/gallery/stage3/18.jpg",
      // "/assets/gallery/stage3/19.jpg",
      // "/assets/gallery/stage3/20.jpg",
      // "/assets/gallery/stage3/21.jpg",
      // "/assets/gallery/stage3/22.jpg",
      // "/assets/gallery/stage3/23.jpg",
      // "/assets/gallery/stage3/24.jpg",
      // "/assets/gallery/stage3/25.jpg",
      // "/assets/gallery/stage3/26.jpg",
      // "/assets/gallery/stage3/27.jpg",
      // "/assets/gallery/stage3/28.jpg",
      // "/assets/gallery/stage3/29.jpg",
      // "/assets/gallery/stage3/30.jpg",
    ],
  },
];
