export const GALLERY = [
  {
    id: 1,
    title: "Tutorial",
    image: "/assets/gallery/tutorial/1.jpg",
    videos: [
      // "https://www.youtube.com/watch?v=EvMhUnO9yBM",
      // "https://www.youtube.com/watch?v=LnI6t-nGIm4",
      // "https://www.youtube.com/watch?v=Ou_uGgsntHI"
    ],
    photos: [
      "/assets/gallery/tutorial/1.jpg",
      "/assets/gallery/tutorial/2.jpg",
      "/assets/gallery/tutorial/3.jpg",
      "/assets/gallery/tutorial/4.jpg",
      "/assets/gallery/tutorial/5.jpg",
      "/assets/gallery/tutorial/6.jpg",
      "/assets/gallery/tutorial/7.jpg",
      "/assets/gallery/tutorial/8.jpg",
      "/assets/gallery/tutorial/9.jpg",
      "/assets/gallery/tutorial/10.jpg",
      "/assets/gallery/tutorial/11.jpg",
      "/assets/gallery/tutorial/12.jpg",
      "/assets/gallery/tutorial/13.jpg",
      "/assets/gallery/tutorial/14.jpg",
      "/assets/gallery/tutorial/15.jpg",
      "/assets/gallery/tutorial/16.jpg",
      "/assets/gallery/tutorial/17.jpg",
      "/assets/gallery/tutorial/18.jpg",
      "/assets/gallery/tutorial/19.jpg",
      "/assets/gallery/tutorial/20.jpg",
    ],
  },
  {
    id: 2,
    title: "Shrine Of Renjana",
    image: "/assets/gallery/stage1/1.jpg",
    videos: [
      // "https://www.youtube.com/watch?v=EvMhUnO9yBM",
      // "https://www.youtube.com/watch?v=LnI6t-nGIm4",
      // "https://www.youtube.com/watch?v=Ou_uGgsntHI"
    ],
    photos: [
      "/assets/gallery/stage1/1.jpg",
      "/assets/gallery/stage1/2.jpg",
      "/assets/gallery/stage1/3.jpg",
      "/assets/gallery/stage1/4.jpg",
      "/assets/gallery/stage1/5.jpg",
      "/assets/gallery/stage1/6.jpg",
      "/assets/gallery/stage1/7.jpg",
      "/assets/gallery/stage1/8.jpg",
      "/assets/gallery/stage1/9.jpg",
      "/assets/gallery/stage1/10.jpg",
      "/assets/gallery/stage1/11.jpg",
      "/assets/gallery/stage1/12.jpg",
      "/assets/gallery/stage1/13.jpg",
      "/assets/gallery/stage1/14.jpg",
      "/assets/gallery/stage1/15.jpg",
      "/assets/gallery/stage1/16.jpg",
      "/assets/gallery/stage1/17.jpg",
      "/assets/gallery/stage1/18.jpg",
      "/assets/gallery/stage1/19.jpg",
      "/assets/gallery/stage1/20.jpg",
      "/assets/gallery/stage1/21.jpg",
      "/assets/gallery/stage1/22.jpg",
      "/assets/gallery/stage1/23.jpg",
      "/assets/gallery/stage1/24.jpg",
      "/assets/gallery/stage1/25.jpg",
      "/assets/gallery/stage1/26.jpg",
      "/assets/gallery/stage1/27.jpg",
      "/assets/gallery/stage1/28.jpg",
      "/assets/gallery/stage1/29.jpg",
      "/assets/gallery/stage1/30.jpg",
    ],
  },
];
